In [2]:
def hamming_7_4(s:str):
    assert(len(s)==4)
    p1 = str(int(s[0])^int(s[1])^int(s[3]))
    p2 = str(int(s[0])^int(s[2])^int(s[3]))
    p3 = str(int(s[1])^int(s[2])^int(s[3]))

    return str(p1 + p2 + s[0] + p3 + s[1] + s[2] + s[3])

In [7]:
hamming_7_4("1011")

'0110011'

In [9]:
def hamming_8_4(s:str):
    assert(len(s)==4)
    x = hamming_7_4(s)
    r = 0
    for i in range(7):
        r= r^int(x[i])
    return str(r)+x

In [42]:
print(hamming_8_4("1011"))


00110011


In [43]:
import numpy as np 
generatrice = np.zeros((8,4))

colonnes = [hamming_8_4("1000"),hamming_8_4("0100"),hamming_8_4("0010"),hamming_8_4("0001")]

for i in range(8):
    for j in range(4):
        generatrice[i][j] = colonnes[j][i]
        
print(generatrice)

[[1. 1. 1. 0.]
 [1. 1. 0. 1.]
 [1. 0. 1. 1.]
 [1. 0. 0. 0.]
 [0. 1. 1. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [44]:
code = np.array([[1],[0],[1],[1]])
c = np.dot(generatrice,code)
# print(c)

for i in range(8):
    c[i] = c[i]%2
print(c)


[[0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]]


https://courspython.com/tableaux-numpy.html