In [2]:
def hamming_7_4(s:str):
    assert(len(s)==4)
    p1 = str(int(s[0])^int(s[1])^int(s[3]))
    p2 = str(int(s[0])^int(s[2])^int(s[3]))
    p3 = str(int(s[1])^int(s[2])^int(s[3]))

    return str(p1 + p2 + s[0] + p3 + s[1] + s[2] + s[3])

In [7]:
hamming_7_4("1011")

'0110011'

In [9]:
def hamming_8_4(s:str):
    assert(len(s)==4)
    x = hamming_7_4(s)
    r = 0
    for i in range(7):
        r= r^int(x[i])
    return str(r)+x

In [42]:
print(hamming_8_4("1011"))


00110011


In [43]:
import numpy as np 
generatrice = np.zeros((8,4))

colonnes = [hamming_8_4("1000"),hamming_8_4("0100"),hamming_8_4("0010"),hamming_8_4("0001")]

for i in range(8):
    for j in range(4):
        generatrice[i][j] = colonnes[j][i]
        
print(generatrice)

[[1. 1. 1. 0.]
 [1. 1. 0. 1.]
 [1. 0. 1. 1.]
 [1. 0. 0. 0.]
 [0. 1. 1. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [44]:
code = np.array([[1],[0],[1],[1]])
c = np.dot(generatrice,code)
# print(c)

for i in range(8):
    c[i] = c[i]%2
print(c)


[[0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]]


https://courspython.com/tableaux-numpy.html

In [37]:
def décodage_8_4(s:str):
    assert(len(s)==8)
    g = 0
    for i in range(7):
        g^= int(s[i])

    print(g)

    s1 = int(s[0]) ^ int(s[2]) ^ int(s[4]) ^ int(s[6])
    s2 = int(s[1]) ^ int(s[2]) ^ int(s[5]) ^ int(s[6])
    s3 = int(s[3]) ^ int(s[4]) ^ int(s[5]) ^ int(s[6])

    syndrome = str(s3) + str(s2) + str(s1)
    print(syndrome)

    if g != int(s[7]) : 
        print("Le nombre d'erreur est impair")

        i = int(syndrome,2)
        print(f"si l'erreur est unique, elle se trouve en position {i}.")
        s = s[:i-1] + str(int(s[i-1])^1) + s[i:]
        print(f"La nouvelle chaine est alors {s} ")
    else : 

        print("Le nombre d'erreur est pair")

        if syndrome == "000" : 
            print("Il n'y a pas d'erreur.")
        else: 
            print("Le nombre d'erreur est strictement supérieur à 1.")

In [ ]:
décodage_8_4("11111100")

1
011
Le nombre d'erreur est impair
si l'erreur est unique, elle se trouve en position 3.
La nouvelle chaine est alors 11001100 


In [20]:
a = "abricot"
print(a[:2])
print(a[2:])


ab
ricot
